MVC.Demo03.PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using MVC.Demo03.BLL.Interfaces;
using MVC.Demo03.BLL.Repositories;
using MVC.Demo03.DAL.Models;
using System;
using System.Threading.Tasks;

namespace MVC.Demo03.PL.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _env;

        public DepartmentController( /*IDepartmentRepository departmentRepo*/  IUnitOfWork unitOfWork , IWebHostEnvironment env)
        {
            _unitOfWork = unitOfWork;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {


            var departments = await _unitOfWork.Repository<Department>().GetAll(); 

            return View(departments);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid) // server sidee validation
            {
                _unitOfWork.Repository<Department>().Add(department);

                var count = await _unitOfWork.Complete();
                if (count > 0)
                    return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        [HttpGet]

        public async Task<IActionResult> Details(int? id , string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();

            var department = await _unitOfWork.Repository<Department>().Get(id.Value);

            if (department is null)
                   return NotFound();
            
            return View(department);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int? id) 
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( [FromRoute] int id , Department dept)
        {

            if (id != dept.Id)
                return BadRequest();

            if (!ModelState.IsValid)
                return View(dept);

            try
            {
                _unitOfWork.Repository<Department>().Update(dept);
                await _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1- Log Exception
                // 2- Friendly Message
                if(_env.IsDevelopment())
                ModelState.AddModelError(string.Empty , ex.Message);
                else
                    ModelState.AddModelError(string.Empty, "An Error in Department");

                return View(dept);

            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id,"Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Department dept)
        {
            try
            {
                _unitOfWork.Repository<Department>().Delete(dept);
              await  _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                 ModelState.AddModelError(string.Empty, ex.Message);
                return View(dept);
            }

        }


    }
}

MVC.Demo03.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using MVC.Demo03.BLL.Interfaces;
using MVC.Demo03.BLL.Repositories;
using MVC.Demo03.DAL.Models;
using MVC.Demo03.PL.Helpers;
using MVC.Demo03.PL.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Demo03.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _env;


        public EmployeeController ( IUnitOfWork unitOfWork, IMapper mapper , IWebHostEnvironment env )
        {
           _unitOfWork = unitOfWork;
            _mapper = mapper;
            _env = env;
        }


        public async Task<IActionResult> Index( string SearchInput)
        {
            var employee = Enumerable.Empty<Employee>();
            var EmpRepo = _unitOfWork.Repository<Employee>() as EmployeeRepository;

            if (string.IsNullOrEmpty(SearchInput))
                 employee = await _unitOfWork.Repository<Employee>().GetAll();
            else
                 employee = EmpRepo.SearchByName(SearchInput.ToLower());

            var mappedEmp = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employee);


            return View(mappedEmp);


        }


        public IActionResult Create()
        {
            //ViewData["Departments"] = _departmentRepo.GetAll();
            //ViewBag.Departments = _departmentRepo.GetAll();
            return View();
        }

        [HttpPost]
        public async Task< IActionResult> Create(EmployeeViewModel EmployeeVM)
        {



            if (ModelState.IsValid) // server sidee validation
            {
               EmployeeVM.ImageName = await  DocumentSetting.UploadFile(EmployeeVM.image, "Images");


                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);

           

                _unitOfWork.Repository<Employee>().Add(mappedEmp);

                var count = await _unitOfWork.Complete();

            

                if (count > 0)
                {

                    return RedirectToAction(nameof(Index));
                }


            }
            return View(EmployeeVM);


        }

        [HttpGet]

        public async Task <IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();


            var Employee = await _unitOfWork.Repository<Employee>().Get(id.Value);
            var mappedEmp = _mapper.Map<Employee, EmployeeViewModel>(Employee);


            if (Employee is null)
                return NotFound();
            if (ViewName.Equals("Delete" ,StringComparison.OrdinalIgnoreCase )) 
            TempData["ImageName"] = Employee.imageName;
            

            return View(mappedEmp);
        }

        [HttpGet]

        public async Task<IActionResult>  Edit(int? id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel EmployeeVM)
        {

            if (id != EmployeeVM.Id)
                return BadRequest();

            if (!ModelState.IsValid)
                return View(EmployeeVM);

            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);

                _unitOfWork.Repository<Employee>().Update(mappedEmp);
                await _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1- Log Exception
                // 2- Friendly Message
                if (_env.IsDevelopment())
                    ModelState.AddModelError(string.Empty, ex.Message);
                else
                    ModelState.AddModelError(string.Empty, "An Error in Employee");

                return View(EmployeeVM);

            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeViewModel EmployeeVM)
        {
            try
            {

                EmployeeVM.ImageName = TempData["ImageName"] as string;
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);

                _unitOfWork.Repository<Employee>().Delete(mappedEmp);
               var count = await _unitOfWork.Complete();
                if (count > 0)
                {
                    DocumentSetting.DeleteFile(EmployeeVM.ImageName, "Images");
                return RedirectToAction(nameof(Index));
                }
                return View(EmployeeVM);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(EmployeeVM);
            }

        }

    }
}

MVC.Demo03.PL/Views/Shared/AuthLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
     <link href="~/css/AuthStyle.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
   @RenderBody()
</body>
</html>

MVC.Demo03.PL/Views/Shared/_ButtonsPartial.cshtml
@model int 

        <td>
            <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
                <i class="fas fa-eye"></i> Details
            </a>
        </td>

        <td>
            <a  asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
                <i class="fas fa-edit"></i> Update
            </a>
        </td>

        <td>
            <a  asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
                <i class="fas fa-trash"></i> Delete
            </a>
        </td>

MVC.Demo03.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC.Demo03.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC.Demo03.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC.Demo03.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationsScriptsSection", required: false)
</body>
</html>